-- USER SUBSCRIPTIONS
DROP TABLE IF EXISTS user_subscriptions;
-- USERS
DROP TABLE IF EXISTS users;
-- ITEMS
DROP TABLE IF EXISTS items;
-- LOGS
DROP TABLE IF EXISTS request_logs;
-- SUBSCRIPTIONS
DROP TABLE IF EXISTS subscription_tiers;